name: APK Yigish Bot

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Run Buildozer
      run: |
        pip install --user --upgrade buildozer build cython virtualenv
        yes | buildozer android debug || true
